public class GroomingGuide_CC {

    public PageReference GroomingGuideHome() {
        return Page.GroomingGuideHomePage;
    }
    
    public PageReference GatherSupplies() {
        return Page.GroomingGatherSuppliesPage;
    }
    
    public PageReference PreBath() {
        return Page.GroomingPreBathPage;
    }
    
    public PageReference Bath() {
        return Page.GroomingBathPage;
    }
    
    public PageReference PostBath() {
        return Page.GroomingPostBathPage;
    }
}